version: "2"
services:
  node:
    build:
      context: .
      dockerfile: Dockerfile
    user: "node"
    working_dir: /home/node/app
    environment:
      - NODE_ENV=production
    volumes:
      - ./:/home/node/app
    ports:
      - "${PORT:-3000}:${PORT:-3000}"
    command: "npm start"